### ISSUE TITLE
Properly closing live query

### ISSUE THREAD

**Issue by appy-one** [appy-one/acebase-client#50]
There currently is no way to stop a realtime query from delivering results, besides if returning `false` in one of the event callbacks. Waiting for a callback to happen might take a long time, so we need way to stop a realtime query upon request.

Suggestion:
```js
const query = db.query('book').filter('rating', '==', ).on('add', bookAdded);
const snaps = await query.get();
// Some time later, stop the realtime query
await query.stop();
```

### Discussed in https://github.com/appy-one/acebase/discussions/108

<div type='discussions-op-text'>

<sup>Originally posted by **donl** May 22, 2022</sup>
When a live query is no longer needed, what is the correct way to unsubscribe and destroy it?</div>

**Comment by appy-one** [comment]
Looks like I was too quick to draw - this originally was an `acebase` issue. @TELECI-PROJECT you were have an issue using `acebase-client` v1.17.0 browser dist. Have you updated to the latest version to check if the issue has been resolved in the meantime?

**Comment by TELECI-PROJECT** [comment]
Hi, thanks, I don't see any errors in console after updating to the latest version (Acebase Client v1.20 and Acebase v1.27).

**Comment by appy-one** [comment]
Great!

[![Spread the word](https://user-images.githubusercontent.com/26569719/169265089-3d593555-e1ad-4390-986b-877ac2c38a47.svg)](https://twitter.com/intent/tweet?button=&url=https://github.com/appy-one/acebase&text=I'm+using+@AcebaseRealtime+in+my+project+to+make+my+life+easier!&button=)  [![contribute](https://user-images.githubusercontent.com/26569719/169265318-30c4c6a5-7c89-46a0-a7a2-ef433a8192f4.svg)](https://github.com/appy-one/acebase#contributing) [![Sponsor AceBase](https://user-images.githubusercontent.com/26569719/168233053-8e56b243-4140-40ab-9a30-4cb3cc149bfe.svg)](https://github.com/sponsors/appy-one)
