### ISSUE TITLE
error: child key for path "default/cache" cannot be empty

### ISSUE THREAD

**Issue by donl** [appy-one/acebase-client#53]
```
Subscription "notify_child_added" on path "/" canceled because of an error: child key for path "default/cache" cannot be empty
```

This had been working previously before a recent update. I'm basically using a copy of the webmanager notify subscription functions to browse the database.

If I disable the cache, it appears to work as before.

Any suggestions?

Thanks in advance!

**Comment by appy-one** [comment]
I managed to reproduce the issue, looking into it
